install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - git clone https://github.com/rhazdon/hugo-theme-hello-friend-ng.git themes/hello-friend-ng

script:
  - hugo

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: master # or master if you are using the two-repository approach